version: { cpe_uri: "cpe:/a:mariadb:mariadb:5.5.60" version: "1.1.0" benchmark_document: "CIS Oracle MySQL Community Server 5.6" }
benchmark_id: "mysql-daemon-least-privilege"
benchmark_id: "mysql-pwd-not-in-environ"
benchmark_id: "mysql-pwd-not-in-profiles"
benchmark_id: "mysql-datadir-permissions"
benchmark_id: "mysql-log-bin-basename-permissions"
benchmark_id: "mysql-log-error-permissions"
benchmark_id: "mysql-slow-query-log-permissions"
benchmark_id: "mysql-slowquerylog-error-permissions"
benchmark_id: "mysql-relay-log-basename-permissions"
benchmark_id: "mysql-general-query-log-permissions"
benchmark_id: "mysql-ssl-keys-permissions"
benchmark_id: "mysql-plugin-dir-permissions"
benchmark_id: "mysql-no-test-database"
benchmark_id: "mysql-local-infile-disabled"
benchmark_id: "mysql-no-skip-grant-tables"
benchmark_id: "mysql-skip-symbolic-links-enabled"
benchmark_id: "mysql-daemon-memcached-disabled"
benchmark_id: "mysql-secure-file-priv-not-empty"
benchmark_id: "mysql-only-admins-have-full-access"
benchmark_id: "mysql-only-admins-have-file-priv"
benchmark_id: "mysql-only-admins-have-super-priv"
benchmark_id: "mysql-only-admins-have-shutdown-priv"
benchmark_id: "mysql-only-admins-have-create-user-priv"
benchmark_id: "mysql-only-admins-have-grant-priv"
benchmark_id: "mysql-only-non-slave-have-repl-slave-priv"
benchmark_id: "mysql-limited-dml-ddl-grants"
benchmark_id: "mysql-log-error-not-empty"
benchmark_id: "mysql-log-raw-disabled"
benchmark_id: "mysql-old-passwords-disabled"
benchmark_id: "mysql-secure-auth-enabled"
benchmark_id: "mysql-no-passwords-in-config"
benchmark_id: "mysql-no-auto-create-user"
benchmark_id: "mysql-no-blank-passwords"
benchmark_id: "mysql-password-policy-enabled"
benchmark_id: "mysql-no-wildcard-hostnames"
benchmark_id: "mysql-no-anonymous-accounts"

