benchmark_configs: {
  id: "aslr-enabled"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure address space layout randomization (ASLR) is enabled"
    description:
      "Address space layout randomization (ASLR) is an exploit mitigation "
      "technique which randomly arranges the address space of key data areas "
      "of a process."
    rationale:
      "Randomly placing virtual memory regions will make it difficult to "
      "write memory page exploits as the memory placement will be "
      "consistently shifting."
    remediation:
      "Set the following parameter in /etc/sysctl.conf or a /etc/sysctl.d/* "
      "file:\n"
      "```\n"
      "kernel.randomize_va_space = 2\n"
      "```\n"
      "Run the following command to set the active kernel parameter:\n"
      "```\n"
      "# sysctl -w kernel.randomize_va_space=2\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"kernel.randomize_va_space *=.*\""
      "        expected_regex: \"kernel.randomize_va_space *= *2\""
      "      }"
      "    }"
      "    non_compliance_msg: \"a config file in /etc/sysctl.d/ disabled ASLR\""
      "    file_display_command: \"grep -l 'kernel.randomize_va_space' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "etc-issue-permissions"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure permissions on /etc/issue are configured"
    description:
      "The contents of the /etc/issue file are displayed to users prior to "
      "login for local terminals."
    rationale:
      "If the /etc/issue file does not have the correct ownership it could "
      "be modified by unauthorized users with incorrect or misleading "
      "information."
    remediation:
      "Run the following commands to set permissions on /etc/issue:\n"
      "```\n"
      "# chown root:root /etc/issue\n"
      "# chmod 644 /etc/issue\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/issue\"}}"
      "    permission:{"
      "      set_bits: 0444"
      "      clear_bits: 0133"
      "      bits_should_match: BOTH_SET_AND_CLEAR"
      "      user: {name: \"root\" should_own: true}"
      "      group: {name: \"root\" should_own: true}"
      "    }"
      "  }"
      "}"
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/issue\"}}"
      "    existence:{should_exist:false}"
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "packet-redirect-sending-disabled"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure packet redirect sending is disabled"
    description:
      "ICMP Redirects are used to send routing information to other hosts. As a host\n"
      "itself does not act as a router (in a host only configuration), there is no\n"
      "need to send redirects."
    rationale:
      "An attacker could use a compromised host to send invalid ICMP redirects to\n"
      "other router devices in an attempt to corrupt routing and have users access a\n"
      "system set up by the attacker as opposed to a valid system."
    remediation:
      "Set the following parameters in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.conf.all.send_redirects = 0\n"
      "net.ipv4.conf.default.send_redirects = 0\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.conf.all.send_redirects=0\n"
      "# sysctl -w net.ipv4.conf.default.send_redirects=0\n"
      "# sysctl -w net.ipv4.route.flush=1\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.all.send_redirects *=.*\""
      "        expected_regex: \"net.ipv4.conf.all.send_redirects *= *0\""
      "      }"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.default.send_redirects *=.*\""
      "        expected_regex: \"net.ipv4.conf.default.send_redirects *= *0\""
      "      }"
      "    }"
      "    non_compliance_msg: \"a config file in /etc/sysctl.d/ enables send_redirects\""
      "    file_display_command: \"grep -l 'send_redirects' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "source-routed-packets-not-accepted"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure source routed packets are not accepted"
    description:
      "In networking, source routing allows a sender to partially or fully specify\n"
      "the route packets take through a network. In contrast, non-source routed\n"
      "packets travel a path determined by routers in the network. In some cases,\n"
      "systems may not be routable or reachable from some locations (e.g. private\n"
      "addresses vs. Internet routable), and so source routed packets would need to\n"
      "be used."
    rationale:
      "Setting net.ipv4.conf.all.accept_source_route, and \n"
      "net.ipv4.conf.default.accept_source_route to 0 disables the system from \n"
      "accepting source routed packets. Assume this system was capable of routing \n"
      "packets to Internet routable addresses on one interface and private addresses \n"
      "on another interface. Assume that the private addresses were not routable to \n"
      "the Internet routable addresses and vice versa. Under normal routing \n"
      "circumstances, an attacker from the Internet routable addresses could not use \n"
      "the system as a way to reach the private address systems. If, however, source \n"
      "routed packets were allowed, they could be used to gain access to the private \n"
      "address systems as the route could be specified, rather than rely on routing \n"
      "protocols that did not allow this routing."
    remediation:
      "Set the following parameters in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.conf.all.accept_source_route = 0\n"
      "net.ipv4.conf.default.accept_source_route = 0\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.conf.all.accept_source_route=0\n"
      "# sysctl -w net.ipv4.conf.default.accept_source_route=0\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d/\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.all.accept_source_route *=.*\""
      "        expected_regex: \"net.ipv4.conf.all.accept_source_route *= *0\""
      "      }"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.default.accept_source_route *=.*\""
      "        expected_regex: \"net.ipv4.conf.default.accept_source_route *= *0\""
      "      }"
      "    }"
      "    non_compliance_msg: \"a config file in /etc/sysctl.d/ enables accept_source_route\""
      "    file_display_command: \"grep -l 'accept_source_route' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "broadcast-icmp-requests-ignored"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure broadcast ICMP requests are ignored"
    description:
      "Setting net.ipv4.icmp_echo_ignore_broadcasts to 1 will cause the system to\n"
      "ignore all ICMP echo and timestamp requests to broadcast and multicast\n"
      "addresses."
    rationale:
      "Accepting ICMP echo and timestamp requests with broadcast or multicast\n"
      "destinations for your network could be used to trick your host into starting\n"
      "or participating) in a Smurf attack. A Smurf attack relies on an attacker\n"
      "sending large amounts of ICMP broadcast messages with a spoofed source\n"
      "address. All hosts receiving this message and responding would send echo-reply\n"
      "messages back to the spoofed address, which is probably not routable. If many\n"
      "hosts respond to the packets, the amount of traffic on the network could be\n"
      "significantly multiplied."
    remediation:
      "Set the following parameters in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.icmp_echo_ignore_broadcasts = 1\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1\n"
      "# sysctl -w net.ipv4.route.flush=1\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d/\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.icmp_echo_ignore_broadcasts *=.*\""
      "        expected_regex: \"net.ipv4.icmp_echo_ignore_broadcasts *= *1\""
      "      }"
      "    }"
      "    non_compliance_msg: \"config files in /etc/sysctl.d/ do not enable echo_ignore_broadcasts\""
      "    file_display_command: \"grep -l 'echo_ignore_broadcasts' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "bogus-icmp-responses-ignored"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure bogus ICMP responses are ignored"
    description:
      "Setting icmp_ignore_bogus_error_responses to 1 prevents the kernel from\n"
      "logging bogus responses (RFC-1122 non-compliant) from broadcast reframes,\n"
      "keeping file systems from filling up with useless log messages."
    rationale:
      "Some routers (and some attackers) will send responses that violate RFC-1122\n"
      "and attempt to fill up a log file system with many useless error messages."
    remediation:
      "Set the following parameter in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.icmp_ignore_bogus_error_responses = 1\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1\n"
      "# sysctl -w net.ipv4.route.flush=1\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d/\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.icmp_ignore_bogus_error_responses *=.*\""
      "        expected_regex: \"net.ipv4.icmp_ignore_bogus_error_responses *= *1\""
      "      }"
      "    }"
      "    non_compliance_msg: \"config files in /etc/sysctl.d/ do not enable icmp_ignore_bogus_error_responses\""
      "    file_display_command: \"grep -l 'icmp_ignore_bogus_error_responses' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "reverse-path-filtering-enabled"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure Reverse Path Filtering is enabled"
    description:
      "Setting net.ipv4.conf.all.rp_filter and net.ipv4.conf.default.rp_filter to 1\n"
      "forces the Linux kernel to utilize reverse path filtering on a received packet\n"
      "to determine if the packet was valid. Essentially, with reverse path\n"
      "filtering, if the return packet does not go out the same interface that the\n"
      "corresponding source packet came from, the packet is dropped (and logged if\n"
      "log_martians is set)."
    rationale:
      "Setting these flags is a good way to deter attackers from sending your system\n"
      "bogus packets that cannot be responded to. One instance where this feature\n"
      "breaks down is if asymmetrical routing is employed. This would occur when\n"
      "using dynamic routing protocols (bgp, ospf, etc) on your system. If you are\n"
      "using asymmetrical routing on your system, you will not be able to enable this\n"
      "feature without breaking the routing."
    remediation:
      "Set the following parameters in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.conf.all.rp_filter = 1\n"
      "net.ipv4.conf.default.rp_filter = 1\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.conf.all.rp_filter=1\n"
      "# sysctl -w net.ipv4.conf.default.rp_filter=1\n"
      "# sysctl -w net.ipv4.route.flush=1\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d/\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.all.rp_filter *=.*\""
      "        expected_regex: \"net.ipv4.conf.all.rp_filter *= *1\""
      "      }"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.conf.default.rp_filter *=.*\""
      "        expected_regex: \"net.ipv4.conf.default.rp_filter *= *1\""
      "      }"
      "    }"
      "    non_compliance_msg: \"config files in /etc/sysctl.d/ do not enable rp_filter\""
      "    file_display_command: \"grep -l 'rp_filter' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "tcp-syn-cookies-enabled"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure TCP SYN Cookies is enabled"
    description:
      "When tcp_syncookies is set, the kernel will handle TCP SYN packets normally\n"
      "until the half-open connection queue is full, at which time, the SYN cookie\n"
      "functionality kicks in. SYN cookies work by not using the SYN queue at all.\n"
      "Instead, the kernel simply replies to the SYN with a SYN|ACK, but will include\n"
      "a specially crafted TCP sequence number that encodes the source and\n"
      "destination IP address and port number and the time the packet was sent. A\n"
      "legitimate connection would send the ACK packet of the three way handshake\n"
      "with the specially crafted sequence number. This allows the system to verify\n"
      "that it has received a valid response to a SYN cookie and allow the\n"
      "connection, even though there is no corresponding SYN in the queue."
    rationale:
      "Attackers use SYN flood attacks to perform a denial of service attacked on a\n"
      "system by sending many SYN packets without completing the three way handshake.\n"
      "This will quickly use up slots in the kernel's half-open connection queue and\n"
      "prevent legitimate connections from succeeding. SYN cookies allow the system\n"
      "to keep accepting valid connections, even if under a denial of service attack."
    remediation:
      "Set the following parameters in /etc/sysctl.conf or a /etc/sysctl.d/* file:\n"
      "```\n"
      "net.ipv4.tcp_syncookies = 1\n"
      "```\n"
      "Run the following commands to set the active kernel parameters:\n"
      "```\n"
      "# sysctl -w net.ipv4.tcp_syncookies=1\n"
      "# sysctl -w net.ipv4.route.flush=1\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{files_in_dir:{"
      "      dir_path:\"/etc/sysctl.d/\""
      "      recursive: true"
      "    }}"
      "    content_entry: {"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \"net.ipv4.tcp_syncookies *=.*\""
      "        expected_regex: \"net.ipv4.tcp_syncookies *= *1\""
      "      }"
      "    }"
      "    non_compliance_msg: \"config files in /etc/sysctl.d/ do not enable tcp_syncookies\""
      "    file_display_command: \"grep -l 'tcp_syncookies' /etc/sysctl.d/*\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "etc-passwd-permissions"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure permissions on /etc/passwd are configured"
    description:
      "The /etc/passwd file contains user account information that is used by many\n"
      "system utilities and therefore must be readable for these utilities to\n"
      "operate."
    rationale:
      "It is critical to ensure that the /etc/passwd file is protected from\n"
      "unauthorized write access. Although it is protected by default, the file\n"
      "permissions could be changed either inadvertently or through malicious\n"
      "actions."
    remediation:
      "Run the following command to set permissions on /etc/passwd:\n"
      "```\n"
      "# chown root:root /etc/passwd\n"
      "# chmod 644 /etc/passwd\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/passwd\"}}"
      "    permission:{"
      "      set_bits: 0444"
      "      clear_bits: 0133"
      "      bits_should_match: BOTH_SET_AND_CLEAR"
      "      user: {name: \"root\" should_own: true}"
      "      group: {name: \"root\" should_own: true}"
      "    }"
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "etc-group-permissions"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure permissions on /etc/group are configured"
    description:
      "The /etc/group file contains a list of all the valid groups defined in the\n"
      "system. The command below allows read/write access for root and read access\n"
      "for everyone else."
    rationale:
      "The /etc/group file needs to be protected from unauthorized changes by non\n"
      "privileged users, but needs to be readable as this information is used with\n"
      "many non-privileged programs."
    remediation:
      "Run the following command to set permissions on /etc/group:\n"
      "```\n"
      "# chown root:root /etc/group\n"
      "# chmod 644 /etc/group\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group\"}}"
      "    permission:{"
      "      set_bits: 0444"
      "      clear_bits: 0133"
      "      bits_should_match: BOTH_SET_AND_CLEAR"
      "      user: {name: \"root\" should_own: true}"
      "      group: {name: \"root\" should_own: true}"
      "    }"
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "etc-group-dash-permissions"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure permissions on /etc/group- are configured"
    description:
      "The /etc/group- file contains a backup list of all the valid groups defined in\n"
      "the system."
    rationale:
      "It is critical to ensure that the /etc/group- file is protected from\n"
      "unauthorized access. Although it is protected by default, the file permissions\n"
      "could be changed either inadvertently or through malicious actions."
    remediation:
      "Run the following command to set permissions on /etc/group-:\n"
      "```\n"
      "# chown root:root /etc/group-\n"
      "# chmod u-x,go-wx /etc/group-\n"
      "```\n"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group-\"}}"
      "    permission:{"
      "      clear_bits: 0133"
      "      user: {name: \"root\" should_own: true}"
      "      group: {name: \"root\" should_own: true}"
      "    }"
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "password-fields-not-empty"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure password fields are not empty"
    description:
      "An account with an empty password field means that anybody may log in as that\n"
      "user without providing a password."
    rationale:
      "All accounts must have passwords or be locked to prevent the account from\n"
      "being used by an unauthorized user."
    remediation:
      "If any accounts in the /etc/shadow file do not have a password, run the\n"
      "following command to lock the account until it can be determined why it does\n"
      "not have a password:\n"
      "```\n"
      "# passwd -l <username>\n"
      "```\n"
      "Also, check to see if the account is logged in and investigate what it is\n"
      "being used for to determine if it needs to be forced off."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/shadow\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:.*:.*:.*:.*:.*:.*:.*\""
      "        expected_regex: \".*:.+:.*:.*:.*:.*:.*:.*:.*\""
      "      }"
      "    }"
      "    non_compliance_msg: \"there are empty password fields in /etc/shadow\""
      "    file_display_command: \"awk -F: '($2 == \\\"\\\" ) { print $1 \\\" does not have a password \\\"}' /etc/shadow\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "passwd-no-legacy-plus-entries"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no legacy \"+\" entries exist in /etc/passwd"
    description:
      "The character + in various files used to be markers for systems to insert data\n"
      "from NIS maps at a certain point in a system configuration file. These entries\n"
      "are no longer required on most systems, but may exist in files that have been\n"
      "imported from other platforms."
    rationale:
      "These entries may provide an avenue for attackers to gain privileged access on\n"
      "the system."
    remediation: "Remove any legacy '+' entries from /etc/passwd if they exist."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/passwd\"}}"
      "    content_entry:{"
      "      match_type: NONE_MATCH"
      "      match_criteria: {"
      "        filter_regex: \"\\\\+:.*\""
      "        expected_regex: \"\\\\+:.*\""
      "      }"
      "    }"
      "    non_compliance_msg: \"there are legacy '+' entries in /etc/passwd\""
      "    file_display_command: \"grep '^\\\\+:' /etc/passwd\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "shadow-no-legacy-plus-entries"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no legacy \"+\" entries exist in /etc/shadow"
    description:
      "The character + in various files used to be markers for systems to insert data\n"
      "from NIS maps at a certain point in a system configuration file. These entries\n"
      "are no longer required on most systems, but may exist in files that have been\n"
      "imported from other platforms."
    rationale: "These entries may provide an avenue for attackers to gain privileged access on the system."
    remediation: "Remove any legacy '+' entries from /etc/shadow if they exist."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/shadow\"}}"
      "    content_entry:{"
      "      match_type: NONE_MATCH"
      "      match_criteria: {"
      "        filter_regex: \"\\\\+:.*\""
      "        expected_regex: \"\\\\+:.*\""
      "      }"
      "    }"
      "    non_compliance_msg: \"there are legacy '+' entries in /etc/shadow\""
      "    file_display_command: \"grep '^\\\\+:' /etc/shadow\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "group-no-legacy-plus-entries"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no legacy \"+\" entries exist in /etc/group"
    description:
      "The character + in various files used to be markers for systems to insert data\n"
      "from NIS maps at a certain point in a system configuration file. These entries\n"
      "are no longer required on most systems, but may exist in files that have been\n"
      "imported from other platforms."
    rationale:
      "These entries may provide an avenue for attackers to gain privileged access on\n"
      "the system."
    remediation: "Remove any legacy '+' entries from /etc/group if they exist."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group\"}}"
      "    content_entry:{"
      "      match_type: NONE_MATCH"
      "      match_criteria: {"
      "        filter_regex: \"\\\\+:.*\""
      "        expected_regex: \"\\\\+:.*\""
      "      }"
      "    }"
      "    non_compliance_msg: \"there are legacy '+' entries in /etc/group\""
      "    file_display_command: \"grep '^\\\\+:' /etc/group\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "root-is-only-uid-0-account"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure root is the only UID 0 account"
    description: "Any account with UID 0 has superuser privileges on the system."
    rationale:
      "This access must be limited to only the default root account and only from the\n"
      "system console. Administrative access must be through an unprivileged account\n"
      "using an approved mechanism as noted in Item 5.6 Ensure access to the su\n"
      "command is restricted."
    remediation: "Remove any users other than root with UID 0 or assign them a new UID if appropriate"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/passwd\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:0:.*:.*:.*:.*\""
      "        expected_regex: \"root:.*:0:.*:.*:.*:.*\""
      "      }"
      "    }"
      "    non_compliance_msg: \"there's a non-root user with uid 0 in /etc/passwd\""
      "    file_display_command: \"awk -F: '($3 == 0) { print $1 }' /etc/passwd\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "no-duplicate-uids"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no duplicate UIDs exist"
    description:
      "Although the useradd program will not let you create a duplicate User ID\n"
      "UID), it is possible for an administrator to manually edit the /etc/passwd\n"
      "file and change the UID field."
    rationale:
      "Users must be assigned unique UIDs for accountability and to ensure\n"
      "appropriate access protections."
    remediation:
      "Based on the results of the audit script, establish unique UIDs and review all\n"
      "files owned by the shared UIDs to determine which UID they are supposed to\n"
      "belong to."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/passwd\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:.*:.*:.*:.*:.*\""
      "        expected_regex: \".*:.*:(\\\\d+):.*:.*:.*:.*\""
      "        group_criteria: {"
      "          group_index: 1"
      "          type: UNIQUE"
      "        }"
      "      }"
      "    }"
      "    non_compliance_msg: \"there are duplicate UIDs\""
      "    file_display_command: \"#!/bin/bash\\ncut -f3 -d\\\":\\\" /etc/passwd | sort -n | uniq -c | while read x ; do\\n  [ -z \\\"$x\\\" ] && break\\n  set - $x\\n  if [ $1 -gt 1 ]; then\\n    users=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/passwd | xargs)\\n    echo \\\"Duplicate UID ($2): $users\\\"\\n  fi\\ndone\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "no-duplicate-gids"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no duplicate GIDs exist"
    description:
      "Although the groupadd program will not let you create a duplicate Group ID\n"
      "GID), it is possible for an administrator to manually edit the /etc/group file\n"
      "and change the GID field."
    rationale: "User groups must be assigned unique GIDs for accountability and to ensure appropriate access protections."
    remediation:
      "Based on the results of the audit script, establish unique GIDs and review all\n"
      "files owned by the shared GID to determine which group they are supposed to\n"
      "belong to."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:.*:.*\""
      "        expected_regex: \".*:.*:(\\\\d+):.*\""
      "        group_criteria: {"
      "          group_index: 1"
      "          type: UNIQUE"
      "        }"
      "      }"
      "    }"
      "    non_compliance_msg: \"there are duplicate GIDs\""
      "    file_display_command: \"#!/bin/bash\\ncut -f3 -d\\\":\\\" /etc/group | sort -n | uniq -c | while read x ; do\\n  [ -z \\\"$x\\\" ] && break\\n  set - $x\\n  if [ $1 -gt 1 ]; then\\n    groups=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/group | xargs)\\n    echo \\\"Duplicate GID ($2): $groups\\\"\\n  fi\\ndone\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "no-duplicate-user-names"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no duplicate user names exist"
    description:
      "Although the useradd program will not let you create a duplicate user name, it\n"
      "is possible for an administrator to manually edit the /etc/passwd file and\n"
      "change the user name."
    rationale:
      "If a user is assigned a duplicate user name, it will create and have access to\n"
      "files with the first UID for that username in /etc/passwd . For example, if\n"
      "\"test4\" has a UID of 1000 and a subsequent \"test4\" entry has a UID of 2000\n"
      "logging in as \"test4\" will use UID 1000. Effectively the UID is shared which\n"
      "is a security problem."
    remediation:
      "Based on the results of the audit script, establish unique user names for the\n"
      "users. File ownerships will automatically reflect the change as long as the\n"
      "users have unique UIDs."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/passwd\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:.*:.*:.*:.*:.*\""
      "        expected_regex: \"(.*):.*:.*:.*:.*:.*:.*\""
      "        group_criteria: {"
      "          group_index: 1"
      "          type: UNIQUE"
      "        }"
      "      }"
      "    }"
      "    non_compliance_msg: \"there are duplicate user names\""
      "    file_display_command: \"#!/bin/bash\\ncut -f1 -d\\\":\\\" /etc/passwd | sort -n | uniq -c | while read x ; do\\n  [ -z \\\"$x\\\" ] && break\\n  set - $x\\n  if [ $1 -gt 1 ]; then\\n    uids=$(awk -F: '($1 == n) { print $3 }' n=$2 /etc/passwd | xargs)\\n    echo \\\"Duplicate User Name ($2): $uids\\\"\\n  fi\\ndone\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "no-duplicate-group-names"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure no duplicate group names exist"
    description:
      "Although the groupadd program will not let you create a duplicate group name,\n"
      "it is possible for an administrator to manually edit the /etc/group file and\n"
      "change the group name."
    rationale:
      "If a group is assigned a duplicate group name, it will create and have access\n"
      "to files with the first GID for that group in /etc/group . Effectively, the\n"
      "GID is shared, which is a security problem."
    remediation:
      "Based on the results of the audit script, establish unique names for the user\n"
      "groups. File group ownerships will automatically reflect the change as long as\n"
      "the groups have unique GIDs."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group\"}}"
      "    content_entry:{"
      "      match_type: ALL_MATCH_ANY_ORDER"
      "      match_criteria: {"
      "        filter_regex: \".*:.*:.*:.*\""
      "        expected_regex: \"(.*):.*:.*:.*\""
      "        group_criteria: {"
      "          group_index: 1"
      "          type: UNIQUE"
      "        }"
      "      }"
      "    }"
      "    non_compliance_msg: \"there are duplicate group names\""
      "    file_display_command: \"#!/bin/bash\\ncut -f1 -d\\\":\\\" /etc/group | sort -n | uniq -c | while read x ; do\\n  [ -z \\\"$x\\\" ] && break\\n  set - $x\\n  if [ $1 -gt 1 ]; then\\n    gids=$(gawk -F: '($1 == n) { print $3 }' n=$2 /etc/group | xargs)\\n    echo \\\"Duplicate Group Name ($2): $gids\\\"\\n  fi\\ndone\""
      "  }"
      "}"
  }
}
benchmark_configs: {
  id: "shadow-group-empty"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:10" version: "1.0.0" }
    title: "Ensure shadow group is empty"
    description:
      "The shadow group allows system programs which require access the ability to\n"
      "read the /etc/shadow file. No users should be assigned to the shadow group."
    rationale:
      "Any users assigned to the shadow group would be granted read access to the\n"
      "etc/shadow file. If attackers can gain read access to the /etc/shadow file,\n"
      "they can easily run a password cracking program against the hashed passwords\n"
      "to break them. Other security information that is stored in the /etc/shadow\n"
      "file (such as expiration) could also be useful to subvert additional user\n"
      "accounts."
    remediation:
      "Remove all users from the shadow group, and change the primary group of any\n"
      "users with shadow as their primary group."
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "check_alternatives:{"
      "  file_checks:{"
      "    files_to_check:{single_file:{path:\"/etc/group\"}}"
      "    content_entry:{"
      "      match_type: NONE_MATCH"
      "      match_criteria: {"
      "        filter_regex: \"shadow:[^:]*:[^:]*:[^:]+\""
      "        expected_regex: \"shadow:[^:]*:[^:]*:[^:]+\""
      "      }"
      "    }"
      "    non_compliance_msg: \"a shadow group exists in /etc/group\""
      "    file_display_command: \"grep ^shadow:[^:]*:[^:]*:[^:]+ /etc/group\""
      "  }"
      "}"
  }
}
