version: { cpe_uri: "cpe:/o:debian:debian_linux:12" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }

benchmark_id: "access-control-permission-modification-events-collected"
benchmark_id: "access-to-su-restricted"
benchmark_id: "accounts-in-etc-passwd-use-shadowed-passwords"
benchmark_id: "actions-as-another-user-logged"
benchmark_id: "aide-installed"
benchmark_id: "apparmor-enabled-bootloader"
benchmark_id: "apparmor-installed"
benchmark_id: "aslr-enabled"
benchmark_id: "at-cron-restricted-to-authorized-users"
benchmark_id: "attempts-to-use-chacl-recorded"
benchmark_id: "attempts-to-use-chcon-recorded"
benchmark_id: "attempts-to-use-setfacl-recorded"
benchmark_id: "attempts-to-use-usermod-recorded"
benchmark_id: "audit-backlog-limit-sufficient"
benchmark_id: "auditd-installed"
benchmark_id: "auditd-service-enabled"
benchmark_id: "audit-log-not-auto-deleted"
benchmark_id: "audit-log-storage-size-configured"
benchmark_id: "auditing-prior-to-auditd-enabled"
benchmark_id: "automounting-disabled"
benchmark_id: "avahi-disabled"
benchmark_id: "bogus-icmp-responses-ignored"
benchmark_id: "bootloader-config-permissions"
benchmark_id: "bootloader-password-set"
benchmark_id: "broadcast-icmp-requests-ignored"
benchmark_id: "changes-to-sudoers-collected"
benchmark_id: "chrony-configured"
benchmark_id: "core-dumps-restricted"
benchmark_id: "cramfs-module-not-available"
benchmark_id: "cron-daemon-enabled"
benchmark_id: "cron-daily-permissions"
benchmark_id: "cron-d-permissions"
benchmark_id: "cron-hourly-permissions"
benchmark_id: "cron-monthly-permissions"
benchmark_id: "crontab-permissions"
benchmark_id: "cron-weekly-permissions"
benchmark_id: "cups-disabled"
benchmark_id: "dccp-mounting-disabled"
benchmark_id: "default-group-for-root-account-is-gid-0"
benchmark_id: "default-user-shell-timeout-900-or-less"
benchmark_id: "dhcp-server-disabled"
benchmark_id: "disable-gnome-automount-removable-media"
benchmark_id: "disable-user-list-enabled"
benchmark_id: "dnsmasq-service-disabled"
benchmark_id: "dns-server-disabled"
benchmark_id: "dot-files-not-group-world-writable"
benchmark_id: "enforcing-apparmor-profiles"
benchmark_id: "ensure-apparmor-profiles-enforce-complain"
benchmark_id: "ensure-audit-config-immutable"
benchmark_id: "ensure-audit-configuration-files-group-configured"
benchmark_id: "ensure-audit-configuration-files-mode-configured"
benchmark_id: "ensure-audit-configuration-files-owner-configured"
benchmark_id: "ensure-audit-log-dir-mode-configured"
benchmark_id: "ensure-audit-log-group-configured"
benchmark_id: "ensure-audit-log-mode-configured"
benchmark_id: "ensure-audit-log-owner-configured"
benchmark_id: "ensure-audit-tools-group-owner-configured"
benchmark_id: "ensure-audit-tools-mode-configured"
benchmark_id: "ensure-audit-tools-owner-configured"
benchmark_id: "ensure-bluetooth-services-disabled"
benchmark_id: "ensure-chrony-running-as-user-chrony"
benchmark_id: "ensure-cryptographic-mechanisms-audit-tools"
benchmark_id: "ensure-default-user-umask-configured"
benchmark_id: "ensure-disable-gnome-automount-removable-media-not-overridden"
benchmark_id: "events-modifying-system-net-env-collected"
benchmark_id: "ensure-ftp-client-not-installed"
benchmark_id: "ensure-gdm-autorun-never-enabled"
benchmark_id: "ensure-gdm-autorun-never-is-not-overridden"
benchmark_id: "ensure-gdm-removed"
benchmark_id: "ensure-gdm-screen-locks-cannot-be-overridden"
benchmark_id: "ensure-gdm-screen-locks-when-user-is-idle"
benchmark_id: "ensure-journald-forwardtosyslog-disabled"
benchmark_id: "ensure-journald-storage-configured"
benchmark_id: "ensure-libpam-pwquality-installed"
benchmark_id: "ensure-nologin-not-in-shells"
benchmark_id: "ensure-pam-faillock-enabled"
benchmark_id: "ensure-pam-pwhistory-enabled"
benchmark_id: "ensure-pam-pwquality-enabled"
benchmark_id: "ensure-pam-unix-enabled"
benchmark_id: "ensure-password-failed-attempts-lockout-includes-root-account"
benchmark_id: "ensure-password-failed-attempts-lockout-is-configured"
benchmark_id: "ensure-password-unlock-time-is-configured"
benchmark_id: "ensure-privileged-commands-are-collected"
benchmark_id: "ensure-root-password-is-set"
benchmark_id: "ensure-root-umask-configured"
benchmark_id: "ensure-rsyslog-not-receive-log-from-client"
benchmark_id: "ensure-single-logging-system"
benchmark_id: "ensure-single-time-sync-daemon"
benchmark_id: "ensure-sshd-ciphers-configured"
benchmark_id: "ensure-sshd-clientalive-configured"
benchmark_id: "ensure-systemd-journal-remote-not-enabled"
benchmark_id: "ensure-ufw-service-enabled"
benchmark_id: "ensure-using-single-firewall"
benchmark_id: "etc-group-dash-permissions"
benchmark_id: "etc-group-permissions"
benchmark_id: "etc-gshadow-dash-permissions"
benchmark_id: "etc-gshadow-permissions"
benchmark_id: "etc-issue-net-permissions"
benchmark_id: "etc-issue-permissions"
benchmark_id: "etc-passwd-dash-permissions"
benchmark_id: "etc-passwd-permissions"
benchmark_id: "etc-shadow-dash-permissions"
benchmark_id: "etc-shadow-passwords-not-empty"
benchmark_id: "etc-shadow-permissions"
benchmark_id: "etc-shells-permissions"
benchmark_id: "events-modifying-date-time-info-collected"
benchmark_id: "events-modifying-system-mac-collected"
benchmark_id: "events-modifying-user-group-info-collected"
benchmark_id: "file-deletion-events-by-users-collected"
benchmark_id: "filesystem-integrity-checked"
benchmark_id: "freevxfs-module-not-available"
benchmark_id: "ftp-server-disabled"
benchmark_id: "gdm-login-banner-configured"
benchmark_id: "groups-from-etc-passwd-in-etc-group"
benchmark_id: "hfs-module-not-available"
benchmark_id: "hfsplus-mounting-disabled"
benchmark_id: "home-nodev"
benchmark_id: "home-nosuid"
benchmark_id: "http-proxy-server-disabled"
benchmark_id: "icmp-redirects-not-accepted"
benchmark_id: "imap-pop3-server-disabled"
benchmark_id: "inactive-password-lock-30-days-or-less"
benchmark_id: "ip6tables-default-deny-policy"
benchmark_id: "ip6tables-loopback-traffic-configured"
benchmark_id: "ip6tables-open-ports-rules-configured"
benchmark_id: "ip-forwarding-disabled"
benchmark_id: "iptables-default-deny-policy"
benchmark_id: "iptables-loopback-traffic-configured"
benchmark_id: "iptables-open-ports-rules-configured"
benchmark_id: "iptables-packages-are-installed"
benchmark_id: "iptables-persistent-not-installed-with-ufw"
benchmark_id: "ipv6-router-advertisements-not-accepted"
benchmark_id: "jffs2-module-not-available"
benchmark_id: "journald-is-configured-to-compress-large-log-files"
benchmark_id: "journald-is-configured-to-send-logs-to-rsyslog"
benchmark_id: "journald-service-enabled"
benchmark_id: "kernel-module-loading-unloading-collected"
benchmark_id: "last-password-change-date-in-past"
benchmark_id: "ldap-client-not-installed"
benchmark_id: "ldap-server-disabled"
benchmark_id: "local-login-warning-configured"
benchmark_id: "logfile-permissions"
benchmark_id: "login-defs-strong-password-hashing"
benchmark_id: "login-logout-events-collected"
benchmark_id: "mail-transfer-agent-is-configured-for-localonly-mode"
benchmark_id: "motd-configured"
benchmark_id: "motd-permissions"
benchmark_id: "network-fs-service-disabled"
benchmark_id: "nftables-base-chains-exist"
benchmark_id: "nftables-default-deny-policy"
benchmark_id: "nftables-is-installed"
benchmark_id: "nftables-loopback-traffic-configured"
benchmark_id: "nftables-not-in-use-with-iptables"
benchmark_id: "nftables-rules-are-permanent"
benchmark_id: "nftables-service-enabled"
benchmark_id: "nftables-table-exists"
benchmark_id: "nis-client-not-installed"
benchmark_id: "nis-server-disabled"
benchmark_id: "no-duplicate-gids"
benchmark_id: "no-duplicate-group-names"
benchmark_id: "no-duplicate-uids"
benchmark_id: "no-duplicate-user-names"
benchmark_id: "no-unowned-files-or-dirs"
benchmark_id: "no-world-writable-files"
benchmark_id: "opasswd-permissions"
benchmark_id: "overlayfs-mounting-disabled"
benchmark_id: "packet-redirect-sending-disabled"
benchmark_id: "pam-unix-nullok-not-included"
benchmark_id: "pam-unix-remember-not-included"
benchmark_id: "pam-unix-strong-hashing-algorithm"
benchmark_id: "pam-unix-use-authtok"
benchmark_id: "password-dictionary-check-enabled"
benchmark_id: "password-difok-changed-characters-configured"
benchmark_id: "password-expiration-365-days-or-less"
benchmark_id: "password-expiration-warning-days-7-or-more"
benchmark_id: "password-history-enforce-for-root"
benchmark_id: "password-history-enforce-use-authtok"
benchmark_id: "password-history-remember-configured"
benchmark_id: "password-maxrepeat-configured"
benchmark_id: "password-maxsequence-configured"
benchmark_id: "password-minimum-length-configured"
benchmark_id: "password-quality-check-enforced"
benchmark_id: "password-quality-enforced-for-root"
benchmark_id: "ptrace-scope-restricted"
benchmark_id: "rds-mounting-disabled"
benchmark_id: "reauthentication-for-privilege-escalation-not-disabled"
benchmark_id: "remote-login-warning-configured"
benchmark_id: "reverse-path-filtering-enabled"
benchmark_id: "root-gid-zero-check"
benchmark_id: "root-gid-zero-group-check"
benchmark_id: "root-is-only-uid-0-account"
benchmark_id: "root-path-integrity"
benchmark_id: "rpcbind-not-in-use"
benchmark_id: "rsh-client-not-installed"
benchmark_id: "rsync-disabled"
benchmark_id: "rsyslog-log-creation-file-configured"
benchmark_id: "rsyslog-service-enabled"
benchmark_id: "samba-disabled"
benchmark_id: "sctp-mounting-disabled"
benchmark_id: "secure-icmp-redirects-not-accepted"
benchmark_id: "separate-partition-home"
benchmark_id: "separate-partition-shm"
benchmark_id: "separate-partition-var"
benchmark_id: "separate-partition-var-log"
benchmark_id: "separate-partition-var-log-audit"
benchmark_id: "separate-partition-var-tmp"
benchmark_id: "session-initiation-info-collected"
benchmark_id: "shadow-group-empty"
benchmark_id: "shm-nodev"
benchmark_id: "shm-noexec"
benchmark_id: "shm-nosuid"
benchmark_id: "snmp-server-disabled"
benchmark_id: "source-routed-packets-not-accepted"
benchmark_id: "squashfs-mounting-disabled"
benchmark_id: "sshd-access-configured"
benchmark_id: "sshd-banner-configured"
benchmark_id: "sshd-config-permissions"
benchmark_id: "sshd-disable-forwarding-configured"
benchmark_id: "sshd-gssapi-authentication-disabled"
benchmark_id: "sshd-hostbasedauthentication-disabled"
benchmark_id: "sshd-private-host-key-permissions"
benchmark_id: "sshd-public-host-key-permissions"
benchmark_id: "ssh-ignorerhosts-enabled"
benchmark_id: "ssh-logingrace-one-minute-or-less"
benchmark_id: "ssh-loglevel-appropriate"
benchmark_id: "ssh-maxauthtries-4-or-less"
benchmark_id: "ssh-maxsessions-4-or-less"
benchmark_id: "ssh-maxstartups-configured"
benchmark_id: "ssh-pam-enabled"
benchmark_id: "ssh-permitemptypasswords-disabled"
benchmark_id: "ssh-permituserenvironments-disabled"
benchmark_id: "ssh-root-login-disabled"
benchmark_id: "strong-key-exchange-algos-used"
benchmark_id: "strong-mac-algorithms-used"
benchmark_id: "successful-file-system-mounts-collected"
benchmark_id: "sudo-authentication-timeout-is-configured-correctly"
benchmark_id: "sudo-commands-use-pty"
benchmark_id: "sudo-is-installed"
benchmark_id: "sudolog-actions-collected"
benchmark_id: "sudo-log-file-exists"
benchmark_id: "suspicious-packets-logged"
benchmark_id: "system-accounts-secured"
benchmark_id: "system-disabled-when-audit-logs-full"
benchmark_id: "systemd-journal-remote-installed"
benchmark_id: "systemd-journal-upload-enabled"
benchmark_id: "systemd-timesyncd-configured"
benchmark_id: "ensure-systemd-timesyncd-enabled"
benchmark_id: "system-warns-on-audit-logs-low-space"
benchmark_id: "talk-client-not-installed"
benchmark_id: "tcp-syn-cookies-enabled"
benchmark_id: "telnet-client-not-installed"
benchmark_id: "tftp-server-service-disabled"
benchmark_id: "time-synchronization-in-use"
benchmark_id: "tipc-mounting-disabled"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-noexec"
benchmark_id: "tmp-nosuid"
benchmark_id: "udf-mounting-disabled"
benchmark_id: "ufw-default-deny-policy"
benchmark_id: "ufw-is-installed"
benchmark_id: "ufw-loopback-traffic-configured"
benchmark_id: "ufw-open-ports-rules-configured"
benchmark_id: "ufw-uninstalled-or-disabled-with-iptables"
benchmark_id: "ufw-uninstalled-or-disabled-with-nftables"
benchmark_id: "unsuccessful-file-access-attempts-collected"
benchmark_id: "usb_storage-mounting-disabled"
benchmark_id: "users-own-home-dirs"
benchmark_id: "users-password-for-escalation"
benchmark_id: "var-log-audit-nodev"
benchmark_id: "var-log-audit-noexec"
benchmark_id: "var-log-audit-nosuid"
benchmark_id: "var-log-nodev"
benchmark_id: "var-log-noexec"
benchmark_id: "var-log-nosuid"
benchmark_id: "var-nodev"
benchmark_id: "var-nosuid"
benchmark_id: "var-tmp-nodev"
benchmark_id: "var-tmp-noexec"
benchmark_id: "var-tmp-nosuid"
benchmark_id: "http-server-disabled"
benchmark_id: "wireless-interfaces-are-disabled"
benchmark_id: "xdcmp-not-enabled"
benchmark_id: "xinetd-service-disabled"
benchmark_id: "x-server-service-disabled"
benchmark_id: "ensure-latest-libpam-installed"
