version: { cpe_uri: "cpe:/o:cos:cos_linux:117" version: "1.0.0" benchmark_document: "CIS Container-Optimized OS" }
benchmark_id: "udf-mounting-disabled-cos"
benchmark_id: "tmp-configured-cos"
benchmark_id: "var-nodev-cos"
benchmark_id: "var-nosuid-cos"
benchmark_id: "var-noexec-cos"
benchmark_id: "tmp-nodev-cos"
benchmark_id: "tmp-nosuid-cos"
benchmark_id: "tmp-noexec-cos"
benchmark_id: "home-nodev-cos"
benchmark_id: "shm-nodev-cos"
benchmark_id: "shm-nosuid-cos"
benchmark_id: "shm-noexec-cos"
benchmark_id: "automounting-disabled"
benchmark_id: "dm-verity-installed-cos-93"
benchmark_id: "bootloader-permissions-cos"
benchmark_id: "auth-for-single-user-required-cos"
benchmark_id: "core-dumps-restricted-cos"
benchmark_id: "nx-enabled"
benchmark_id: "aslr-enabled"
benchmark_id: "apparmor-installed"
benchmark_id: "motd-configured-cos"
benchmark_id: "local-login-warning-configured-cos"
benchmark_id: "remote-login-warning-configured-cos"
benchmark_id: "motd-permissions-cos"
benchmark_id: "etc-issue-permissions-cos"
benchmark_id: "etc-issue-net-permissions-cos"
benchmark_id: "chrony-installed-cos"
benchmark_id: "chrony-configured-cos"
benchmark_id: "x-window-system-not-installed-cos"
benchmark_id: "nfs-rpc-disabled-cos"
benchmark_id: "rsync-disabled-cos"
benchmark_id: "packet-redirect-sending-disabled-cos"
benchmark_id: "source-routed-packets-not-accepted-cos"
benchmark_id: "icmp-redirects-not-accepted-cos"
benchmark_id: "secure-icmp-redirects-not-accepted-cos"
benchmark_id: "suspicious-packets-logged-cos"
benchmark_id: "broadcast-icmp-requests-ignored-cos"
benchmark_id: "bogus-icmp-responses-ignored-cos"
benchmark_id: "reverse-path-filtering-enabled-cos"
benchmark_id: "tcp-syn-cookies-enabled-cos"
benchmark_id: "ipv6-router-advertisements-not-accepted-cos"
benchmark_id: "iptables-installed-cos"
benchmark_id: "stackdriver-correct-container"
benchmark_id: "logging-service-running"
benchmark_id: "logging-configured"
benchmark_id: "journald-compress-large-log-files-cos"
benchmark_id: "journald-write-to-persistent-disk-cos"
benchmark_id: "logfile-permissions-cos"
benchmark_id: "logrotate-configured-cos"
benchmark_id: "sshd-config-permissions"
benchmark_id: "sshd-private-host-key-permissions"
benchmark_id: "sshd-public-host-key-permissions"
benchmark_id: "ssh-protocol-set-to-2"
benchmark_id: "ssh-loglevel-appropriate"
benchmark_id: "ssh-x11-forwarding-disabled"
benchmark_id: "ssh-maxauthtries-4-or-less"
benchmark_id: "ssh-ignorerhosts-enabled"
benchmark_id: "ssh-hostbasedauthentication-disabled"
benchmark_id: "ssh-root-login-disabled"
benchmark_id: "ssh-permitemptypasswords-disabled"
benchmark_id: "ssh-permituserenvironments-disabled"
benchmark_id: "strong-ciphers-used"
benchmark_id: "strong-mac-algorithms-used-cos"
benchmark_id: "strong-key-exchange-algos-used"
benchmark_id: "ssh-idle-timeout-interval-configured-cos"
benchmark_id: "ssh-logingrace-one-minute-or-less-cos"
benchmark_id: "ssh-warning-banner-configured-cos"
benchmark_id: "ssh-pam-enabled"
benchmark_id: "ssh-allowtcpforwarding-disabled-cos"
benchmark_id: "ssh-maxstartups-configured-cos"
benchmark_id: "ssh-maxsessions-4-or-less-cos"
benchmark_id: "password-creation-reqs-configured-cos"
benchmark_id: "password-reuse-limited-cos"
benchmark_id: "password-hashing-algorithm-sha-512-cos"
benchmark_id: "password-expiration-365-days-or-less-cos"
benchmark_id: "minimum-days-between-password-changes-7-or-more-cos"
benchmark_id: "password-expiration-warning-days-7-or-more"
benchmark_id: "inactive-password-lock-30-days-or-less-cos"
benchmark_id: "last-password-change-date-in-past"
benchmark_id: "system-accounts-secured-cos"
benchmark_id: "default-group-for-root-account-is-gid-0"
benchmark_id: "default-user-umask-027-or-more-restrictive-cos"
benchmark_id: "default-user-shell-timeout-900-or-less"
benchmark_id: "root-login-restricted-to-system-console"
benchmark_id: "access-to-su-restricted-cos"
benchmark_id: "etc-passwd-permissions"
benchmark_id: "etc-shadow-permissions"
benchmark_id: "etc-group-permissions"
benchmark_id: "etc-gshadow-permissions"
benchmark_id: "etc-passwd-dash-permissions-cos"
benchmark_id: "etc-shadow-dash-permissions"
benchmark_id: "etc-group-dash-permissions"
benchmark_id: "etc-gshadow-dash-permissions"
benchmark_id: "password-fields-not-empty"
benchmark_id: "passwd-no-legacy-plus-entries"
benchmark_id: "shadow-no-legacy-plus-entries"
benchmark_id: "group-no-legacy-plus-entries"
benchmark_id: "root-is-only-uid-0-account"
benchmark_id: "root-path-integrity-cos"
benchmark_id: "home-dirs-exist"
benchmark_id: "home-dirs-750-or-more-restrictive"
benchmark_id: "users-own-home-dirs"
benchmark_id: "dot-files-not-group-world-writable"
benchmark_id: "no-forward-files"
benchmark_id: "no-netrc-files"
benchmark_id: "netrc-files-not-group-world-accessible"
benchmark_id: "no-rhost-files"
benchmark_id: "groups-from-etc-passwd-in-etc-group"
benchmark_id: "no-duplicate-uids"
benchmark_id: "no-duplicate-gids"
benchmark_id: "no-duplicate-user-names"
benchmark_id: "no-duplicate-group-names"
benchmark_id: "shadow-group-empty"
benchmark_id: "ipv6-default-deny-firewall-policy-cos"
benchmark_id: "configure-ipv6-loopback-cos"
benchmark_id: "ipv6-outbound-established-connections-configured-cos"
benchmark_id: "default-deny-firewall-policy-cos"
benchmark_id: "configure-loopback-cos"
benchmark_id: "outbound-established-connections-configured-cos"

# Generic linux checks that should be L2 in COS.
profile_level_override: {
  level: 2
  benchmark_id: "udf-mounting-disabled-cos"
  benchmark_id: "stackdriver-correct-container"
  benchmark_id: "logging-configured"
  benchmark_id: "ssh-maxauthtries-4-or-less"
  benchmark_id: "strong-mac-algorithms-used-cos"
  benchmark_id: "ssh-idle-timeout-interval-configured-cos"
  benchmark_id: "ssh-logingrace-one-minute-or-less-cos"
  benchmark_id: "ssh-warning-banner-configured-cos"
  benchmark_id: "ssh-allowtcpforwarding-disabled-cos"
  benchmark_id: "ssh-maxstartups-configured-cos"
  benchmark_id: "ssh-maxsessions-4-or-less-cos"
  benchmark_id: "password-reuse-limited-cos"
  benchmark_id: "password-hashing-algorithm-sha-512-cos"
  benchmark_id: "password-expiration-365-days-or-less-cos"
  benchmark_id: "minimum-days-between-password-changes-7-or-more-cos"
  benchmark_id: "password-expiration-warning-days-7-or-more"
  benchmark_id: "inactive-password-lock-30-days-or-less-cos"
  benchmark_id: "etc-shadow-dash-permissions"
  benchmark_id: "etc-gshadow-dash-permissions"
  benchmark_id: "home-dirs-exist"
  benchmark_id: "home-dirs-750-or-more-restrictive"
  benchmark_id: "users-own-home-dirs"
  benchmark_id: "dot-files-not-group-world-writable"
  benchmark_id: "no-forward-files"
  benchmark_id: "no-netrc-files"
  benchmark_id: "netrc-files-not-group-world-accessible"
  benchmark_id: "no-rhost-files"
  benchmark_id: "groups-from-etc-passwd-in-etc-group"
}
