version: { cpe_uri: "cpe:/o:cos:cos_linux:89" version: "1.0.0" benchmark_document: "CIS Container-Optimized OS" }
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "shm-noexec"
benchmark_id: "automounting-disabled"
benchmark_id: "auth-for-single-user-required-cos"
benchmark_id: "nx-enabled"
benchmark_id: "aslr-enabled"
benchmark_id: "apparmor-installed"
benchmark_id: "local-login-warning-configured"
benchmark_id: "remote-login-warning-configured"
benchmark_id: "etc-issue-permissions"
benchmark_id: "chrony-installed-cos"
benchmark_id: "chrony-configured-cos-89"
benchmark_id: "x-window-system-not-installed-cos"
benchmark_id: "nfs-rpc-disabled"
benchmark_id: "rsync-disabled-cos"
benchmark_id: "packet-redirect-sending-disabled"
benchmark_id: "source-routed-packets-not-accepted"
benchmark_id: "broadcast-icmp-requests-ignored"
benchmark_id: "bogus-icmp-responses-ignored"
benchmark_id: "reverse-path-filtering-enabled"
benchmark_id: "tcp-syn-cookies-enabled"
benchmark_id: "iptables-installed-cos"
benchmark_id: "journald-write-to-persistent-disk"
benchmark_id: "sshd-config-permissions"
benchmark_id: "sshd-private-host-key-permissions"
benchmark_id: "sshd-public-host-key-permissions"
benchmark_id: "ssh-protocol-set-to-2"
benchmark_id: "ssh-loglevel-appropriate"
benchmark_id: "ssh-x11-forwarding-disabled"
benchmark_id: "ssh-ignorerhosts-enabled"
benchmark_id: "ssh-hostbasedauthentication-disabled"
benchmark_id: "ssh-root-login-disabled"
benchmark_id: "ssh-permitemptypasswords-disabled"
benchmark_id: "ssh-permituserenvironments-disabled"
benchmark_id: "strong-ciphers-used"
benchmark_id: "strong-key-exchange-algos-used"
benchmark_id: "ssh-pam-enabled"
benchmark_id: "password-expiration-warning-days-7-or-more"
benchmark_id: "last-password-change-date-in-past"
benchmark_id: "default-group-for-root-account-is-gid-0"
benchmark_id: "root-login-restricted-to-system-console"
benchmark_id: "access-to-su-restricted"
benchmark_id: "etc-passwd-permissions"
benchmark_id: "etc-shadow-permissions"
benchmark_id: "etc-group-permissions"
benchmark_id: "etc-gshadow-permissions"
benchmark_id: "etc-group-dash-permissions"
benchmark_id: "password-fields-not-empty"
benchmark_id: "passwd-no-legacy-plus-entries"
benchmark_id: "shadow-no-legacy-plus-entries"
benchmark_id: "group-no-legacy-plus-entries"
benchmark_id: "root-is-only-uid-0-account"
benchmark_id: "no-duplicate-uids"
benchmark_id: "no-duplicate-gids"
benchmark_id: "no-duplicate-user-names"
benchmark_id: "no-duplicate-group-names"
benchmark_id: "shadow-group-empty"

# Generic linux checks that should be L2 in COS.
profile_level_override: {
  level: 2
  benchmark_id: "password-expiration-warning-days-7-or-more"
}
