version: { cpe_uri: "fallback" version: "2.0.0" benchmark_document: "CIS Distribution Independent Linux" }
benchmark_id: "world-writable-dirs-sticky-fallback"
benchmark_id: "motd-permissions-fallback"
benchmark_id: "etc-issue-permissions-fallback"
benchmark_id: "etc-issue-net-permissions-fallback"
benchmark_id: "chargen-services-disabled-fallback"
benchmark_id: "daytime-services-disabled-fallback"
benchmark_id: "discard-services-disabled-fallback"
benchmark_id: "echo-services-disabled-fallback"
benchmark_id: "time-services-disabled-fallback"
benchmark_id: "rsh-server-disabled-fallback"
benchmark_id: "talk-server-disabled-fallback"
benchmark_id: "telnet-server-disabled-fallback"
benchmark_id: "tftp-server-disabled-fallback"
benchmark_id: "nis-client-not-installed-fallback"
benchmark_id: "rsh-client-not-installed-fallback"
benchmark_id: "talk-client-not-installed-fallback"
benchmark_id: "telnet-client-not-installed-fallback"
benchmark_id: "ldap-client-not-installed-fallback"
benchmark_id: "logfile-permissions-fallback"
benchmark_id: "system-accounts-secured-fallback"
benchmark_id: "default-group-for-root-account-is-gid-0-fallback"
benchmark_id: "default-user-umask-027-or-more-restrictive-fallback"
benchmark_id: "etc-passwd-permissions-fallback"
benchmark_id: "etc-shadow-permissions-fallback"
benchmark_id: "etc-group-permissions-fallback"
benchmark_id: "etc-gshadow-permissions-fallback"
benchmark_id: "etc-passwd-dash-permissions-fallback"
benchmark_id: "etc-shadow-dash-permissions-fallback"
benchmark_id: "etc-group-dash-permissions-fallback"
benchmark_id: "etc-gshadow-dash-permissions-fallback"
benchmark_id: "no-world-writable-files-fallback"
benchmark_id: "no-unowned-files-or-dirs-fallback"
benchmark_id: "no-ungrouped-files-or-dirs-fallback"
benchmark_id: "audit-suid-execs-fallback"
benchmark_id: "audit-sgid-execs-fallback"
benchmark_id: "password-fields-not-empty-fallback"
benchmark_id: "passwd-no-legacy-plus-entries-fallback"
benchmark_id: "shadow-no-legacy-plus-entries-fallback"
benchmark_id: "group-no-legacy-plus-entries-fallback"
benchmark_id: "root-is-only-uid-0-account-fallback"
benchmark_id: "home-dirs-exist-fallback"
benchmark_id: "home-dirs-750-or-more-restrictive-fallback"
benchmark_id: "users-own-home-dirs-fallback"
benchmark_id: "dot-files-not-group-world-writable-fallback"
benchmark_id: "no-forward-files-fallback"
benchmark_id: "no-netrc-files-fallback"
benchmark_id: "netrc-files-not-group-world-accessible-fallback"
benchmark_id: "no-rhost-files-fallback"
benchmark_id: "groups-from-etc-passwd-in-etc-group-fallback"
benchmark_id: "no-duplicate-uids-fallback"
benchmark_id: "no-duplicate-gids-fallback"
benchmark_id: "no-duplicate-user-names-fallback"
benchmark_id: "no-duplicate-group-names-fallback"
benchmark_id: "shadow-group-empty-fallback"
